'use client'

import { useEffect } from 'react'

// Section 25 — the SW is generated by @ducanh2912/next-pwa at build time and
// only in production. Registered here (next-pwa `register: false`) so update
// handling stays explicit.
export function ServiceWorkerRegistrar() {
  useEffect(() => {
    if (process.env.NODE_ENV === 'development') return
    if (!('serviceWorker' in navigator)) return

    navigator.serviceWorker
      .register('/sw.js', { updateViaCache: 'none' })
      .then((reg) => {
        if (reg.waiting) reg.waiting.postMessage({ type: 'SKIP_WAITING' })
      })
      .catch((err) => {
        console.error('[sw] registration failed', err)
      })
  }, [])

  return null
}
